apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: |-
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    jenkins.io/chart-description: A Helm chart for Prow
    jenkins.io/chart-repository: http://chartmuseum.jenkins-x.io
  creationTimestamp: null
  labels:
    app: tide
    chart: prow-0.0.578
    heritage: Tiller
    jenkins.io/app-name: prow
    jenkins.io/app-version: 0.0.578
    release: prow
  name: tide
  namespace: jx
spec: {}
